server:
  port: 8082

spring:
  application:
    name: platform-video-service
  datasource:
    url: jdbc:mysql://localhost:3306/video_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 761320
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

storage:


minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: video-platform
  chunk-dir: video_chunks
  video-dir: videos
  image-dir: video_img
